#! /bin/sh

sxhkd &
ibus-daemon -drx
touchegg &
skypeforlinux &
mailspring --background &
libinput-gestures-setup start 
feh --bg-fil $HOME/Pictures/bg.jpg
compton &

xinput set-prop 16 281 1
xinput set-prop 16 299 1

bspc monitor eDP-1 -d 1 2 3 4 5 
bspc monitor DP-3 -d 6 7 8 9 0

$HOME/Workspace/global/dotfiles/polybar/styles/launch.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

